import pandas as pd
import numpy as np
import statistics as st
from scipy import stats

# SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
iris = pd.read_csv("Iris.csv")
df = pd.DataFrame(data=iris)
df.drop("Species", axis=1, inplace=True)
df.drop("Id",axis=1,inplace=True)

print("The mean of the Sepal Length is :",st.mean(df['SepalLengthCm']))
print("The mean of the Sepal Width is :",st.mean(df['SepalWidthCm']))
print("The mean of the Petal Length is :",st.mean(df['PetalLengthCm']))
print("The mean of the Petal Width is :",st.mean(df['PetalWidthCm']))
print("*"*80)
print("The median of the Sepal Length is :",st.median(df['SepalLengthCm']))
print("The median of the Sepal Width is :",st.median(df['SepalWidthCm']))
print("The median of the Petal Length is :",st.median(df['PetalLengthCm']))
print("The median of the Petal Width is :",st.median(df['PetalWidthCm']))
print("*"*80)
print("The mode of the Sepal Length is :",st.mode(df['SepalLengthCm']))
print("The mode of the Sepal Width is :",st.mode(df['SepalWidthCm']))
print("The mode of the Petal Length is :",st.mode(df['PetalLengthCm']))
print("The mode of the Petal Width is :",st.mode(df['PetalWidthCm']))
print("*"*80)
print("The variance of the Sepal Length is :",st.variance(df['SepalLengthCm']))
print("The variance of the Sepal Width is :",st.variance(df['SepalWidthCm']))
print("The variance of the Petal Length is :",st.variance(df['PetalLengthCm']))
print("The variance of the Petal Width is :",st.variance(df['PetalWidthCm']))
print("*"*80)
print("The standard deviation of the Sepal Length is :",st.stdev(df['SepalLengthCm']))
print("The standard deviation of the Sepal Width is :",st.stdev(df['SepalWidthCm']))
print("The standard deviation of the Petal Length is :",st.stdev(df['PetalLengthCm']))
print("The standard deviation of the Petal Width is :",st.stdev(df['PetalWidthCm']))
print("*"*80)
print("The 25th Quantile of the Sepal Length is :",np.quantile(df['SepalLengthCm'],0.25))
print("The 50th Quantile of the Sepal Length is :",np.quantile(df['SepalLengthCm'],0.50))
print("The 75th Quantile of the Sepal Length is :",np.quantile(df['SepalLengthCm'],0.75))
print("The 95th Quantile of the Sepal Length is :",np.quantile(df['SepalLengthCm'],0.95))
print("*"*80)
print("The 25th Quantile of the Sepal Width is :",np.quantile(df['SepalWidthCm'], 0.25))
print("The 50th Quantile of the Sepal Width is :",np.quantile(df['SepalWidthCm'], 0.50))
print("The 75th Quantile of the Sepal Width is :",np.quantile(df['SepalWidthCm'], 0.75))
print("The 95th Quantile of the Sepal Width is :",np.quantile(df['SepalWidthCm'], 0.95))
print("*"*80)
print("The 25th Quantile of the Petal Length is :",np.quantile(df['PetalLengthCm'], 0.25))
print("The 50th Quantile of the Petal Length is :",np.quantile(df['PetalLengthCm'], 0.50))
print("The 75th Quantile of the Petal Length is :",np.quantile(df['PetalLengthCm'], 0.75))
print("The 95th Quantile of the Petal Length is :",np.quantile(df['PetalLengthCm'], 0.95))
print("*"*80)
print("The 25th Quantile of the Petal Width is :",np.quantile(df['PetalWidthCm'], 0.25))
print("The 50th Quantile of the Petal Width is :",np.quantile(df['PetalWidthCm'], 0.50))
print("The 75th Quantile of the Petal Width is :",np.quantile(df['PetalWidthCm'], 0.75))
print("The 95th Quantile of the Petal Width is :",np.quantile(df['PetalWidthCm'], 0.95))
print("*"*80)


print(df.kurt())